global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*grpc_io.*'
        action: drop

  # Scrape application metrics (if exposed)
  - job_name: 's3-vectors-rag'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'  # If your app exposes metrics

  # Scrape Prometheus own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']